import { USER_TYPES } from "@/constants/shared";

const {
  BROKERAGE_SOCIETY,
  EXCLUSIVE_AGENT,
  INSURANCE_BROKER,
  INSURANCE_COMPANY,
  INSURANCE_COMPANY_COOPERATIVE,
  INSURANCE_COMPANY_INSURTECH,
  INSURANCE_COMPANY_PREPAID_MEDICINE,
  SUPPLIER,
} = USER_TYPES;

export const ORGANIZATION_FILTER_FIELD_NAMES = {
  LOCATION: "location",
  SEGMENT: "segment",
  GENRE: "genre",
  AGE_RANGE: "ageRange",
  SERVICE_TYPE: "serviceType",
  EXPERIENCE_RANGE: "experienceRange",
  INSURANCE_COMPANY_ID: "insuranceCompanyId",
};

const {
  LOCATION,
  SEGMENT,
  GENRE,
  AGE_RANGE,
  EXPERIENCE_RANGE,
  SERVICE_TYPE,
  INSURANCE_COMPANY_ID,
} = ORGANIZATION_FILTER_FIELD_NAMES;

export const ALLOWED_FILTERS_BY_USER_TYPE = {
  [BROKERAGE_SOCIETY]: [LOCATION, SEGMENT, EXPERIENCE_RANGE],
  [EXCLUSIVE_AGENT]: [LOCATION, SEGMENT, GENRE, AGE_RANGE, EXPERIENCE_RANGE],
  [INSURANCE_BROKER]: [LOCATION, SEGMENT, GENRE, AGE_RANGE, EXPERIENCE_RANGE],
  [INSURANCE_COMPANY]: [LOCATION, SEGMENT],
  [INSURANCE_COMPANY_COOPERATIVE]: [LOCATION, SEGMENT],
  [INSURANCE_COMPANY_INSURTECH]: [LOCATION, SEGMENT],
  [INSURANCE_COMPANY_PREPAID_MEDICINE]: [LOCATION, SEGMENT],
  [SUPPLIER]: [LOCATION, SERVICE_TYPE, INSURANCE_COMPANY_ID],
} as const;

