import { USER_TYPES } from "@/constants/shared";

const {
  BROKERAGE_SOCIETY,
  EXCLUSIVE_AGENT,
  INSURANCE_BROKER,
  INSURANCE_COMPANY,
  SUPPLIER,
} = USER_TYPES;

export const ORGANIZATION_FILTER_FIELD_NAMES = {
  LOCATION: "location",
  SEGMENT: "segment",
  GENRE: "genre",
  AGE_RANGE: "ageRange",
  SERVICE_TYPE: "serviceType",
  EXPERIENCE_RANGE: "experienceRange",
};

const { LOCATION, SEGMENT, GENRE, AGE_RANGE, EXPERIENCE_RANGE, SERVICE_TYPE } =
  ORGANIZATION_FILTER_FIELD_NAMES;

export const ALLOWED_FILTERS_BY_USER_TYPE = {
  [BROKERAGE_SOCIETY]: [LOCATION, SEGMENT, EXPERIENCE_RANGE],
  [EXCLUSIVE_AGENT]: [LOCATION, SEGMENT, GENRE, AGE_RANGE, EXPERIENCE_RANGE],
  [INSURANCE_BROKER]: [LOCATION, SEGMENT, GENRE, AGE_RANGE, EXPERIENCE_RANGE],
  [INSURANCE_COMPANY]: [LOCATION, SEGMENT],
  [SUPPLIER]: [LOCATION, SERVICE_TYPE],
} as const;

