export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  QUOTES: "/quotes",
  REGISTER: "/register",
  COMPANIES: "/companies",
  MY_QUOTES: "/my-quotes",
  MY_ACCOUNT: "/my-account",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ORGANIZATIONS: "/organizations",
  HERRAMIENTAS: "/herramientas",
  MODULES: "/herramientas/modulos",
  ADMIN_NEWS: "/herramientas/noticias",
  NOTICIAS: "/noticias",
} as const;
